tools: make-all now generates Makefiles
Woohoo! Can now fully build the firmware from command line!

Expecting <MPLAB-X install dir>/mplab_ide/bin to be on the path and
MPLAB 1.90 or later.

diff --git a/tools/make-all b/tools/make-all
--- a/tools/make-all
+++ b/tools/make-all
@@ -12,6 +12,7 @@ for PROJ in $PROJECTS; do
   echo ===========================================
   echo $PROJ
   echo ===========================================
+  if ! prjMakefilesGenerator.bat firmware/$PROJ; then echo "WARNING: failed to regenerate Makefiles."; fi
   if ! $MAKE -C firmware/$PROJ "$@"; then echo FAILURE ; exit 1 ; fi
 done
 echo SUCCESS
